# my global config
global:
  scrape_interval: %%scrape_interval%%s
  evaluation_interval: 15s 

remote_write:
  - url: '%%remote_write%%'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'home-assistant'
    metrics_path: /api/prometheus
    bearer_token: '%%token%%'
    static_configs:
    - targets: ['%%target_ip%%:%%target_port%%']
      labels:
        latitude: '%%latitude%%'
        longitude: '%%longitude%%'